<a href="https://colab.research.google.com/github/samikshak02/Python-Basic-Projects./blob/master/numpy_session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a1=np.array({2,3,4,5,6,7})
print("1D Array:\n",a1)
print("shape:",a1.shape)
print("Data type:",a1.dtype)
a2 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print("2D Array:\n",a2)
print("shape:",a2.shape)
print("Data type:",a2.dtype)


1D Array:
 {2, 3, 4, 5, 6, 7}
shape: ()
Data type: object
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
Data type: int64


In [6]:

import numpy as np
a1=np.zeros(8)
print("1D Array of zeros:\n",a1)
a2=np.ones((4, 4))
print("\n2D Array of ones:\n",a2)
a3=np.zeros((3, 3))
print("\n3x3 matrixs of zeros:\n",a3)


1D Array of zeros:
 [0. 0. 0. 0. 0. 0. 0. 0.]

2D Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 matrixs of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np
a1=np.arange(1,21,1)
print("Numbers from 0 to 20:\n",a1)
a2=np.arange(10,50,2)
print("\nEven numbers from 10 to 50.:\n",a2)
a3=np.arange(5,101,5)
print("\nNumbers from 5 to 100 (step of 5):\n",a3)

Numbers from 0 to 20:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even numbers from 10 to 50.:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]

Numbers from 5 to 100 (step of 5):
 [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [8]:
import numpy as np
a1=np.linspace(0,5,10)
print("10 equally spaced numbers between 0 to 5:\n",a1)
print("length of array",len(a1))
a2=np.linspace(-10,10,15)
print("\n15 equally spaced numbers between -10 and 10.:\n",a2)
print("length of array",len(a2))


10 equally spaced numbers between 0 to 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
length of array 10

15 equally spaced numbers between -10 and 10.:
 [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
length of array 15


In [9]:
import numpy as np
a1=np.random.rand(10)
print("1D array of 10 random numbers between 0 and 1:\n",a1)
a2=np.random.randn(3,3)
print("\nA 3x3 matrix of random numbers from standard normal distribution:\n",a2)
a3=np.random.randint(10,51,(4,5))
print("\nA 2D array (4x5) of random integers between 10 and 50\n",a3)


1D array of 10 random numbers between 0 and 1:
 [0.95636259 0.05563152 0.69479206 0.7401379  0.71122333 0.78842057
 0.69827478 0.23469486 0.47693313 0.39871836]

A 3x3 matrix of random numbers from standard normal distribution:
 [[ 0.6107242   0.53487552  0.0444387 ]
 [ 0.46946937  0.37608626 -0.89876653]
 [-0.31631128 -0.53836962 -0.25324748]]

A 2D array (4x5) of random integers between 10 and 50
 [[40 43 41 46 28]
 [50 42 11 22 16]
 [18 25 20 47 33]
 [48 36 45 28 15]]


In [15]:
import numpy as np
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
print("Addition:",v1+v2)
print("Subtraction:",v1-v2)
print("Element-wise multiplication:",v1*v2)
print("Dot product:",np.dot(v1,v2))



Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element-wise multiplication: [ 2 12 30 56]
Dot product: 100


In [11]:

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("\n Matrix Addition:",A+B)
print("\nmatrix Multiplication (@):",A@B)
print("\n Element-wise multiplication (*):",A*B)


 Matrix Addition: [[10 10 10]
 [10 10 10]
 [10 10 10]]

matrix Multiplication (@): [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

 Element-wise multiplication (*): [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [12]:
import numpy as np

a1= np.random.randint(1, 101, (4,4))

print("Matrix:")
print(a1)

print("\nShape:", a1.shape)
print("Dimension:", a1.ndim)
print("Total Elements:", a1.size)
print("Data Type:", a1.dtype)
print("Minimum Value:", a1.min())
print("Maximum Value:", a1.max())


Matrix:
[[47 20 72 98]
 [52 27 30 96]
 [62 38 59 17]
 [54 66 21  5]]

Shape: (4, 4)
Dimension: 2
Total Elements: 16
Data Type: int64
Minimum Value: 5
Maximum Value: 98


In [13]:
import numpy as np

a1 = np.random.randint(1, 51, 20)
print("1D Array:")
print(a1)

matrix = a1.reshape(4,5)
print("\n4x5 Matrix:")
print(matrix)

print("\nSum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

print("\nMaximum Value in Each Row:")
print(matrix.max(axis=1))

1D Array:
[32  1 20 29 14 17  1 46 14 38 46 14 11 14  8 35 42 24 38 49]

4x5 Matrix:
[[32  1 20 29 14]
 [17  1 46 14 38]
 [46 14 11 14  8]
 [35 42 24 38 49]]

Sum: 493
Mean: 24.65
Standard Deviation: 14.93075684618834

Maximum Value in Each Row:
[32 46 46 49]


In [14]:
import numpy as np

n = int(input("Enter number of elements: "))

numbers = []

for i in range(n):
    num = float(input("Enter number: "))
    numbers.append(num)

a1 = np.array(numbers)

print("\nArray:")
print(a1)

print("Sum:", np.sum(a1))
print("Mean:", np.mean(a1))
print("Maximum:", np.max(a1))
print("Minimum:", np.min(a1))
print("Standard Deviation:", np.std(a1))

Enter number of elements: 2
Enter number: 3
Enter number: 5

Array:
[3. 5.]
Sum: 8.0
Mean: 4.0
Maximum: 5.0
Minimum: 3.0
Standard Deviation: 1.0
