<a href="https://colab.research.google.com/github/samikshak02/Python-Basic-Projects./blob/master/task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
integer=np.random.randint(10, 101, (5, 6))
print("array:\n", integer)
print("\nshape:\n", integer.shape)
print("\ntotal number of elements:\n", integer.size)
print("\ndatatype:\n", integer.dtype)

array:
 [[73 79 58 97 34 83]
 [92 75 23 38 64 63]
 [70 90 89 22 85 97]
 [20 59 31 17 83 95]
 [41 25 96 87 31 35]]

shape:
 (5, 6)

total number of elements:
 30

datatype:
 int64


In [ ]:
integer=np.random.randint(1, 51,20)
print("\narray:\n",integer)
print("\nminimum value:", integer.min())
print("index of minimum value:", integer.argmin())
print("\nmaximum value:", integer.max())
print("index of maximum value:", integer.argmax())
print("\nsum of all elements:", integer.sum())
print("mean of all elements:", integer.mean())
print("standard deviation:", integer.std())


array:
 [45  2  4 30 35 46 15 10 39 50 32 44 43 29 24 33  5 26  7 16]

minimum value: 2
index of minimum value: 1

maximum value: 50
index of maximum value: 9

sum of all elements: 535
mean of all elements: 26.75
standard deviation: 15.234418269169321


In [ ]:
matrix=np.random.randint(20, 81, (4, 5))
print("Matrix\n",matrix)
print("\nmaximum value:", matrix.max())
print("minimum value:", matrix.min())
print("sum of all elements:", matrix.sum())
print("mean of all elements:", matrix.mean())
print("standard deviation:", matrix.std())
print("sum of each row:", matrix.sum(axis=1))
print("sum of each column:", matrix.sum(axis=0))

Matrix
 [[72 46 46 40 38]
 [44 26 76 44 22]
 [61 80 41 34 57]
 [22 30 34 38 76]]

maximum value: 80
minimum value: 22
sum of all elements: 927
mean of all elements: 46.35
standard deviation: 17.703883754701963
sum of each row: [242 212 273 200]
sum of each column: [199 182 197 156 193]


In [ ]:
array = np.arange(1, 25)
print("Orignal array:\n", array)
a=array.reshape(4, 6)
print("\nreshaped array in (4, 6):\n", a)
print("shape of the array:", a.shape)
b=array.reshape(3, 8)
print("\nreshaped array in (3, 8):\n", b)
print("shape of the array:", b.shape)
c=array.reshape(2, 3, 4)
print("\nreshaped array in (2, 3, 4) 3d array:\n", c)
print("shape of the array:", c.shape)

Orignal array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

reshaped array in (4, 6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape of the array: (4, 6)

reshaped array in (3, 8):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
shape of the array: (3, 8)

reshaped array in (2, 3, 4) 3d array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape of the array: (2, 3, 4)


In [ ]:
arr=np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print("array:\n", arr)
print("\nfirst row:", arr[0])
print("\nlast column:", arr[:,  3])
print("\ncenter 2x2 elements:\n", arr[1:3, 1:3])
print("\neven numbers in the array:\n", arr[arr % 2 == 0])


array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

first row: [10 20 30 40]

last column: [ 40  80 120]

center 2x2 elements:
 [[ 60  70]
 [100 110]]

even numbers in the array:
 [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [2]:
import numpy as np
array= np.random.randint(1, 101, (5, 5))
print("Original Matrix:")
print(array)
print("\nDiagonal Elements:",np.diag(array))
print("\nElements Greater Than 50:", array[array > 50])
array[array < 30] = 0
print("\nModified Matrix:")
print(array)

Original Matrix:
[[26 99 97 36 90]
 [90 87 28 27  5]
 [14 73 16  4 95]
 [65 47  5 31 78]
 [ 3  7 10 40 71]]

Diagonal Elements: [26 87 16 31 71]

Elements Greater Than 50: [99 97 90 90 87 73 95 65 78 71]

Modified Matrix:
[[ 0 99 97 36 90]
 [90 87  0  0  0]
 [ 0 73  0  0 95]
 [65 47  0 31 78]
 [ 0  0  0 40 71]]


In [3]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("Array A:", a)
print("Array B:", b)

print("\nAddition:",a + b)
print("\nSubtraction:",a - b)
print("\nMultiplication:",a * b)
print("\nDivision:",a / b)
print("\nPower (**):",a ** b)
print("\nModulo (%):",a % b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition: [11 22 33 44]

Subtraction: [ 9 18 27 36]

Multiplication: [ 10  40  90 160]

Division: [10. 10. 10. 10.]

Power (**): [     10     400   27000 2560000]

Modulo (%): [0 0 0 0]


In [4]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Element-wise Multiplication:")
print(A * B)
print("\nMatrix Multiplication:")
print("using @:",A @ B)
print("using np.dot:",np.dot(A, B))
#A * B → Multiplies corresponding elements.
#A @ B or np.dot(A, B) → Performs actual matrix multiplication.

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
using @: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
using np.dot: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
import numpy as np

arr = np.random.randn(6,6)
print("Matrix:",arr)
print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("\nMaximum Index:", arr.argmax())
print("Minimum Index:", arr.argmin())
print("\nTop Left 3x3:")
print(arr[:3, :3])
arr[arr < 0] = np.abs(arr[arr < 0])
print("\nModified Matrix:")
print(arr)
print("\nMean:", arr.mean())

Matrix: [[-9.74121384e-01  6.99001177e-01  2.73779673e-01  1.45856559e+00
  -2.82059879e-01 -2.30801234e-01]
 [ 2.62401089e+00  1.04476000e+00  7.00509186e-01  5.66832038e-02
  -1.45433278e-01  1.17933208e+00]
 [ 3.14902783e-01 -3.72985200e-01 -1.37862234e+00 -1.01189394e-02
  -1.27505342e+00 -5.82667354e-01]
 [ 1.44169204e+00  1.24025203e+00  5.24041947e-01 -1.47709173e+00
   1.67704717e-01  5.91842324e-02]
 [ 3.24148257e-01  4.91148494e-02 -6.30088420e-02 -1.21885921e-03
  -1.27573273e+00 -5.35216319e-01]
 [ 7.30401862e-01 -6.19554349e-02 -7.00116650e-01 -1.38884463e+00
   6.04858783e-01 -1.84515970e-01]]

Shape: (6, 6)
Size: 36
Data Type: float64

Maximum Index: 6
Minimum Index: 21

Top Left 3x3:
[[-0.97412138  0.69900118  0.27377967]
 [ 2.62401089  1.04476     0.70050919]
 [ 0.31490278 -0.3729852  -1.37862234]]

Modified Matrix:
[[9.74121384e-01 6.99001177e-01 2.73779673e-01 1.45856559e+00
  2.82059879e-01 2.30801234e-01]
 [2.62401089e+00 1.04476000e+00 7.00509186e-01 5.66832038e-0

In [7]:
import numpy as np

# Generate a 2D array (10 students × 5 subjects)
marks = np.random.randint(30, 101, (10, 5))

# Print the marks array
print("Student Marks:\n")
print(marks)

# Calculate total marks of each student
total = marks.sum(axis=1)

# Calculate average marks of each student
average = marks.mean(axis=1)

# Print total and average
print("\nTotal Marks of Each Student:")
print(total)
print("\nAverage Marks of Each Student:")
print(average)

# Find highest and lowest scorer
highest = total.argmax()
lowest = total.argmin()

print("\nHighest Scorer: Student", highest + 1)
print("Marks:", marks[highest])
print("Total:", total[highest])
print("\nLowest Scorer: Student", lowest + 1)
print("Marks:", marks[lowest])
print("Total:", total[lowest])

# Calculate overall class statistics
print("\nOverall Class Mean:", marks.mean())
print("Overall Class Standard Deviation:", marks.std())

# Extract top 3 students using indexing
top3 = total.argsort()[-3:]
print("\nTop 3 Students (Indices):")
print(top3 + 1)

print("\nMarks of Top 3 Students:")
print(marks[top3])

# Reshape the array (optional demonstration)
reshaped = marks.reshape(5, 10)
print("\nReshaped Array (5 x 10):")
print(reshaped)

Student Marks:

[[ 58  65  84  51 100]
 [ 89  42  67  52  70]
 [ 34  30  78  89  57]
 [ 64  70  76  97  30]
 [ 80  70  42  84  74]
 [ 45  47  54 100  39]
 [ 54  51  87  72  33]
 [ 65  84  35  50  41]
 [ 42  58  81  44  59]
 [ 90  88  52  63  79]]

Total Marks of Each Student:
[358 320 288 337 350 285 297 275 284 372]

Average Marks of Each Student:
[71.6 64.  57.6 67.4 70.  57.  59.4 55.  56.8 74.4]

Highest Scorer: Student 10
Marks: [90 88 52 63 79]
Total: 372

Lowest Scorer: Student 8
Marks: [65 84 35 50 41]
Total: 275

Overall Class Mean: 63.32
Overall Class Standard Deviation: 19.555500504973022

Top 3 Students (Indices):
[ 5  1 10]

Marks of Top 3 Students:
[[ 80  70  42  84  74]
 [ 58  65  84  51 100]
 [ 90  88  52  63  79]]

Reshaped Array (5 x 10):
[[ 58  65  84  51 100  89  42  67  52  70]
 [ 34  30  78  89  57  64  70  76  97  30]
 [ 80  70  42  84  74  45  47  54 100  39]
 [ 54  51  87  72  33  65  84  35  50  41]
 [ 42  58  81  44  59  90  88  52  63  79]]
